# Default values for deps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MySQL configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  fullnameOverride: "mysql"
  architecture: standalone
  image:
    pullPolicy: "Always"
  auth:
    rootPassword: password    # to be provided by CI/CD
  primary:
    extraFlags: "--sort_buffer_size=10M"
    persistence:
      size: 50Gi
    service:
      nodePort: 3306
  initdbScripts:
    init_openmetadata_db_scripts.sql: |
      CREATE DATABASE openmetadata_db;
      CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
      GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
      commit;
    init_airflow_db_scripts.sql: |
      CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
      CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
      GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
      commit;

# ElasticSearch configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/elastic/elasticsearch
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  fullnameOverride: "elasticsearch"
  imagePullPolicy: "Always"
  esJavaOpts: "-Xmx1024m -Xms1024m"
  maxUnavailable: 0
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=20s"
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "2000m"
      memory: "2048M"

# Airflow configurations for helm dependency
# you can find more details about this here https://github.com/airflow-helm/charts
airflow:
  enabled: true
  airflow:
    image:
      repository: docker.getcollate.io/openmetadata/ingestion
      tag: 1.1.7
      pullPolicy: "IfNotPresent"
    executor: "KubernetesExecutor"
    config:
      # This is required for OpenMetadata UI to fetch status of DAGs
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      # OpenMetadata Airflow Apis Plugin DAGs Configuration
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dags"
      # OpenMetadata Airflow Secrets Manager Configuration
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_REGION: ""
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_ACCESS_KEY_ID: ""
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_ACCESS_KEY: ""
    users:
    - username: admin
      password: AgA1lleQwPdI5VJuvkBPOIoDJTwzHWI4yDYvY7m8HEWP4IBFKlw6fKIU+rCs3rncx+LsJVUFOR+bmrKhcs5JptDEFXeZ1DZfQshR1OptJFToH6ysPoOXVVXP/5cbpkcOjpV3UKegL0Jrxi6SXZWnh/TlxwqG/nmrv9+IE/K8+7c3qG2ARb5Ba97D06od1gI5DUxGpwKKwLdduBb5zkyQnV2+zpuEIvEaeU20rfz9DjuPsCSFbmiE41Qq9NcIQQIqgSvs1vqVInTiS/RB91AUO+ELFqnlm3kbrCCdYTFBk/LJc/rAiehSDO0/y1TnoG8EEfXFe0lgA8LMPeJqkIT0+CLmTNXWEgzU4mrDEAwTfd/8oE6N5SPjEMCS2qHOHXePgeL1oBXUrCWJ+lWkQNYtoiOqDVl+1uWZr4RbvO6J+YKLH6Gb1atbK7ojI8O4t50k3pf38PintspBWH1FU8JhCfY6YEIg9VzZTJnEiV/LOx/EbzvcIp8QTHAte4SykWf2bSGM7/lsKipfELN+xf5LuimvlMK6x2n65OD4iSeuJnZBi3RVMW0c6NF7DG4QtrwLS3Dea9/xJVJEkZMFCYDI6fT+nqVQ7iy1QS5pH6Y0/SaqZokZBbs2op76IKFJq6kD3cK+1HHCEAAbgvViMtTVkFpJ+TC1naUIdQRgx0wJjF77tHDkzHvDBldGtwx7Z/CjLRSN9B897A==
      role: Admin
      email: spiderman@superhero.org
      firstName: Peter
      lastName: Parker
  web:
    extraVolumes:
    - name: pod-template
      configMap:
        name: openmetadata-pod-template
        defaultMode: 420
    extraVolumeMounts:
      - name: pod-template
        readOnly: true
        subPath: pod_template.yaml
        mountPath: /opt/airflow/pod_templates/pod_template.yaml
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
  postgresql:
    enabled: false
  workers:
    enabled: false
  flower:
    enabled: false
  redis:
    enabled: false
  externalDatabase:
    type: mysql
    host: mysql
    port: 3306
    database: airflow_db
    user: airflow_user
    passwordSecret: airflow-mysql-secrets
    passwordSecretKey: airflow-mysql-password
  serviceAccount:
    create: true
    name: "airflow"
  scheduler:
    logCleanup:
      enabled: false
  dags:
    persistence:
      enabled: true
      # NOTE: "" means cluster-default
      storageClass: ""
      size: 1Gi
      accessMode: ReadWriteMany
  logs:
    persistence:
      enabled: true
      # empty string means cluster-default
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi
